apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include kuma-versionizer.fullname . }}
  labels:
    {{- include kuma-versionizer.labels . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include kuma-versionizer.labels . | nindent 12 }}
            {{- with .Values.podLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          {{- with .Values.image.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
          - name: kuma-versionizer
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command: [python, /app/kuma-versionizer.py]
            env:
            - name: UPTIME_KUMA_URL
              value: {{ .Values.uptimeKuma.url | quote }}
            - name: UPTIME_KUMA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.uptimeKuma.usernameSecret.name }}
                  key: {{ .Values.uptimeKuma.usernameSecret.key }}
            - name: UPTIME_KUMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.uptimeKuma.passwordSecret.name }}
                  key: {{ .Values.uptimeKuma.passwordSecret.key }}
            - name: SERVICES_CONFIG
              value: {{ .Values.services | toJson | quote }}
            - name: VERIFY_SSL
              value: {{ .Values.verifySSL | quote }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: OnFailure
